Repository mindbody/Conduit, pull requests merged in 2018-08, with the labels that each got.

#106 (Feature) | Allow direct manipulation of XML trees by changing XML and XMLNode to reference types
  CHANGELOG.md
  Sources/Conduit/Auth/Auth.swift
  Sources/Conduit/Networking/Serialization/HTTPRequestSerializer.swift
  Sources/Conduit/Networking/Serialization/JSONRequestSerializer.swift
  Sources/Conduit/Networking/Serialization/XML/SOAPEnvelopeFactory.swift
  Sources/Conduit/Networking/Serialization/XML/XML.swift
  Sources/Conduit/Networking/Serialization/XML/XMLNode.swift
  Sources/Conduit/Networking/Serialization/XML/XMLRequestSerializer.swift
  Sources/Conduit/Networking/URLSessionClient.swift
  Tests/ConduitTests/Networking/Serialization/JSONResponseDeserializerTests.swift
  Tests/ConduitTests/Networking/Serialization/XML/XMLNodeTests.swift
  Tests/ConduitTests/Networking/Serialization/XML/XMLTests.swift
Labels: enhancement

#104 (Feature)|Add customParameters to OAuth2AuthorizationResponse
  CHANGELOG.md
  Conduit.xcodeproj/project.pbxproj
  Sources/Conduit/Auth/AuthorizationCodeGrant/OAuth2AuthorizationResponse.swift
  Sources/Conduit/Auth/AuthorizationCodeGrant/iOS/OAuth2AuthorizationRedirectHandler.swift
  Tests/ConduitTests/Auth/AuthTestUtilities.swift
  Tests/ConduitTests/Auth/OAuth2AuthorizationStrategyTests.swift
Labels: enhancement, help wanted

#108 (Feature) | Find XML nodes matching a given function
  CHANGELOG.md
  Sources/Conduit/Networking/Serialization/XML/XMLNode.swift
  Tests/ConduitTests/Networking/Serialization/XML/XMLNodeTests.swift
Labels: enhancement

#105 (Bugfix)|Change httbin error message to httpbin
  Tests/ConduitTests/start-test-webserver
Labels: documentation, good first issue

#109 (Feature) | Update XMLNode to enable traversing upwards the XML node tree
  CHANGELOG.md
  Conduit.xcodeproj/project.pbxproj
  Sources/Conduit/Networking/Serialization/XML/XMLNode.swift
  Tests/ConduitTests/Networking/Serialization/XML/XMLNodeTests.swift
  Tests/ConduitTests/Networking/Serialization/XML/XMLNodeTestsSubjects.swift
Labels: enhancement
